# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoWindow(object):
    def setupUi(self, VideoWindow):
        VideoWindow.setObjectName("VideoWindow")
        VideoWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(VideoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalLayout.addWidget(self.horizontalScrollBar)
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout.addWidget(self.time_label)
        self.speed_cbox = QtWidgets.QComboBox(self.centralwidget)
        self.speed_cbox.setMinimumSize(QtCore.QSize(50, 0))
        self.speed_cbox.setObjectName("speed_cbox")
        self.speed_cbox.addItem("")
        self.speed_cbox.addItem("")
        self.speed_cbox.addItem("")
        self.speed_cbox.addItem("")
        self.horizontalLayout.addWidget(self.speed_cbox)
        self.horizontalLayout.setStretch(0, 20)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 20)
        self.verticalLayout.setStretch(1, 1)
        VideoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(VideoWindow)
        QtCore.QMetaObject.connectSlotsByName(VideoWindow)

    def retranslateUi(self, VideoWindow):
        _translate = QtCore.QCoreApplication.translate
        VideoWindow.setWindowTitle(_translate("VideoWindow", "MainWindow"))
        self.time_label.setText(_translate("VideoWindow", "xx:xx/xx:xx"))
        self.speed_cbox.setItemText(0, _translate("VideoWindow", "1x"))
        self.speed_cbox.setItemText(1, _translate("VideoWindow", "0.5x"))
        self.speed_cbox.setItemText(2, _translate("VideoWindow", "2x"))
        self.speed_cbox.setItemText(3, _translate("VideoWindow", "3x"))
